### ISSUE TITLE
`struct-updaters` as a separate package?

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-alexis#8]
Should `define-struct-updaters`, `struct-updaters-out`, `struct+updaters-out`, and `get-struct-accessors` from `alexis/util/struct` and `(submod alexis/util/struct get-struct-accessors)` be moved into a separate package?

**Comment by AlexKnauth** [comment]
With the extra version exceptions for this package, I can now use `define-struct-updaters` in Racket v6.0. When installing it however, I got setup errors about `typed/alexis/bool`. So it seems like `typed/alexis/bool` needs a dependency on a newer version of racket.

But, `alexis/util/struct` works fine in 6.0, and doesn't need the dependency.

**Comment by lexi-lambda** [comment]
I apologize for taking so long to give actual feedback on this, but I’ve been trying to figure out what exactly it is that I want to do, and I didn’t expect it would take quite this long. Anyway, I’m still working on this, but I’m most of the way there, I think.

The `get-struct-accessors` function was always intended to be an implementation detail, not really a library, but the functionality it provides is definitely useful independent from `define-struct-updaters`. I have reinvented it as a syntax class instead of a function, and I have extracted it into a new package called [syntax-classes](https://github.com/lexi-lambda/syntax-classes). Once the docs build on the package system, you can look at them, or you can just install them locally.

I have a mostly-complete reimplementation of `alexis/util/struct` using the `struct-id` syntax class. I’ve written documentation for it, but I still need to reimplement `struct-updaters-out`, so once I finish that I’ll upload it to the package system in a separate repo and change this package to reprovide that one. In the meantime, the `struct-id` syntax class should work with lens.

There is a catch, however: syntax-classes-lib depends on functional-lib, which depends on base 6.2, which defeats the whole purpose of doing this extraction, if I understand what you want to do. I’ll also look into getting functional-lib working with earlier versions of Racket, and if it’s too obnoxious, I’ll eliminate the dependency (it shouldn’t be hard to remove, but code reuse is convenient).

**Comment by AlexKnauth** [comment]
> which defeats the whole purpose

(Not necessarily, it makes more sense to depend on `syntax-classes` than it does to depend on `alexis-util`)

Part of the purpose was slimming down the dependencies to the things that it actually depends on. That means if it can't work on 6.0 because of something in `alexis/util/bool`, that makes no sense, because it shouldn't need to depend on `alexis/util/bool`. On the other hand if it depends on 6.2 because of something in a `syntax-local-value` syntax-class, that makes perfect sense, because the struct-lenses actually depend on getting the `syntax-local-value` of the struct-id and doing stuff with it.

(I can also imagine a version of `syntax-classes` for 6.1.1 and lower that wouldn't depend on 6.2, but that shouldn't be the point)

**Comment by AlexKnauth** [comment]
Also, it will be great to use [syntax-classes](https://github.com/lexi-lambda/syntax-classes), I've wanted things like that for a long time, and I've probably created my own versions of these syntax classes several times. It will be good to delete that duplicated code and use a library with proper documentation instead.

**Comment by AlexKnauth** [comment]
I still think `struct-updaters` would be useful on its own, so I'll rewrite this pull request to depend on `syntax-classes` instead, and not provide `get-struct-accessors` in the weird way that it currently does. I'll also make a pull request for `lens` to use `syntax-classes` instead of `get-struct-accessors`.

**Comment by AlexKnauth** [comment]
Closing because [struct-update](https://github.com/lexi-lambda/struct-update) accomplishes this.
